[package]
name = "prolog-rs"
version = "0.1.0"
edition = "2021"
resolver = "1"

[build-dependencies]
lalrpop = "0.19.6"

[dependencies]
clap = { version = "3.0.0-rc.4", features = ["derive"] }
itertools = "0.10.3"
lalrpop-util = "0.19.6"
regex = "1"
rustyline = "9.1.0"
